### ISSUE TITLE
Crashed when i tried to open it

### ISSUE THREAD

**Issue by Techcraft7** [mcmonkey4eva/OpenTKMapMaker#1]
```
Preparing console...
Starting system...

Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\bb10575\Videos\New folder\OpenTKMapMaker-master\OpenTKMapMaker\bin\Debug\data'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at OpenTKMapMaker.Utility.FileHandler.Init() in c:\Users\bb10575\Videos\New folder\OpenTKMapMaker-master\OpenTKMapMaker\Utility\FileHandler.cs:line 31
   at OpenTKMapMaker.Program.Main() in c:\Users\bb10575\Videos\New folder\OpenTKMapMaker-master\OpenTKMapMaker\Program.cs:line 33
2019/02/14 17:33:54 UTC-05:00 [INIT] Console prepared...
2019/02/14 17:33:55 UTC-05:00 [INIT] Test colors: Text Colors: ^1 ^! ^2 ^@ ^3 ^# ^4 ^$ ^5 ^% ^6 ^- ^7 ^& ^8 ^* ^9 ^( ^0 ^) ^a ^A
Text styles: ^b is bold, ^i is italic, ^u is underline, ^s is strike-through, ^O is overline, ^h is highlight, ^j is jello (AKA jiggle), ^e is emphasis, ^t is transparent, ^T is more transparent, ^o is opaque, ^R is random, ^p is pseudo-random, ^k is obfuscated (obfu), ^S is SuperScript, ^l is SubScript (AKA Lower-Text), ^d is Drop-Shadow, ^f is flip, ^r is regular text, ^q is a "quote", and ^n is nothing (escape-symbol).
>
```

**Comment by Techcraft7** [comment]
here is the console text

**Comment by mcmonkey4eva** [comment]
Er, woops. This repo is outdated / unused.

... I should probably bother to mark old repos archived.

If you want a more up-to-date look at the graphics engine work I've been doing, that's here: https://github.com/FreneticLLC/FreneticGameEngine

Doesn't quite come with a level editor at the moment but will in time.
